apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-stvsxudp
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-stvsxudp:f0a7bf7d2740601b93b37e9ddf6619c4b97053a9@sha256:bdf2200b08ee1095f74965a07f2cb1522467de6fad4109344598804074c4d735
        name: container-image  
